# Generated by Django 5.1.3 on 2024-11-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermessage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
